name: 'DevOps Practices for Azure Cosmos DB - GitHub Actions Workflow'
on:
    workflow_dispatch:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
  Build:
    name: 'Build Web App'
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: .NET Restore
        run: dotnet restore SampleApp/WebApp.csproj

      - name: .NET Build
        run: dotnet build SampleApp/WebApp.csproj --configuration Release --no-restore

      - name: .NET Publish
        run: dotnet publish SampleApp/WebApp.csproj --configuration Release --no-build --no-restore --output ./publish

      - name: Upload web app artifact
        uses: actions/upload-artifact@v3
        with:
          name: SampleApp
          path: publish

  Testing:
    name: 'Testing'
    runs-on: windows-latest # Azure Cosmos DB Emulator only supports Windows, although you can run it in a Docker container. https://learn.microsoft.com/azure/cosmos-db/local-emulator#run-on-linux-macos
    steps:
    - name: Repository checkout
      uses: actions/checkout@v4

    - name: Initialize Azure Cosmos DB Emulator
      shell: pwsh
      run: | # Code from https://learn.microsoft.com/azure/cosmos-db/tutorial-setup-ci-cd
        dir "C:\Program Files\Azure Cosmos DB Emulator\"      
        Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"      
        $startEmulatorCmd = "Start-CosmosDbEmulator -NoFirewall -NoUI"
        Write-Host $startEmulatorCmd
        Invoke-Expression -Command $startEmulatorCmd
    
        $Emulator = Get-Item "$env:ProgramFiles\Azure Cosmos DB Emulator\Microsoft.Azure.Cosmos.Emulator.exe"
        $IPAddress = Get-NetIPAddress -AddressFamily IPV4 -AddressState Preferred -PrefixOrigin Manual | Select-Object IPAddress
        
        New-Object PSObject @{
            Emulator = $Emulator.BaseName
            Version = $Emulator.VersionInfo.ProductVersion
            Endpoint = @($(hostname), $IPAddress.IPAddress) | ForEach-Object { "https://${_}:8081/" }
            MongoDBEndpoint = @($(hostname), $IPAddress.IPAddress) | ForEach-Object { "mongodb://${_}:10255/" }
            CassandraEndpoint = @($(hostname), $IPAddress.IPAddress) | ForEach-Object { "tcp://${_}:10350/" }
            GremlinEndpoint = @($(hostname), $IPAddress.IPAddress) | ForEach-Object { "http://${_}:8901/" }
            TableEndpoint = @($(hostname), $IPAddress.IPAddress) | ForEach-Object { "https://${_}:8902/" }
            IPAddress = $IPAddress.IPAddress
        }
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
    - name: Install NPM Azure Cosmos dependency
      run: npm install @azure/cosmos
    - name: Create and test Stored Procedure with Azure Cosmos DB Emulator
      uses: actions/github-script@v6
      with:
        script: | # This is the default connection string for the Azure Cosmos DB Emulator and TLS Reject is disabled for the emulator self-certificate.
            process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
            async function createSP() {       
                const { CosmosClient } = require("@azure/cosmos");
                const endpoint = "https://localhost:8081";
                const key = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==";
                const client = new CosmosClient({ endpoint, key });    
                const { database } =  await client.databases.createIfNotExists({ id: 'SampleDatabase' });
                const { container } =  await database.containers.createIfNotExists({ id: 'SampleContainer' });
                const { sampleStoredProcedure } = require('./StoredProcedures/SampleStoredProcedure.js');    
                try {
                    await container.scripts.storedProcedures.create(sampleStoredProcedure)              
                } catch (e) {
                    if (e.code === 409) {
                        console.log('Stored procedure already exists replacing it with new version.')
                        await container.scripts.storedProcedure(sampleStoredProcedure.id).replace(sampleStoredProcedure) 
                    } else {
                        throw(e)
                    }
                }
                finally{
                    const { resource: results } = await container.scripts.storedProcedure(sampleStoredProcedure.id).execute();
                    console.log(results);  
                }
            }
            createSP().catch(error => {
              console.error("An error occurred: ", error);
            });

    - name: Create and test Trigger
      uses: actions/github-script@v6
      with:
        script: | # This is the default connection string for the Azure Cosmos DB Emulator and TLS Reject is disabled for the emulator self-certificate.
            process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
            async function createTrigger() {
                const { CosmosClient } = require("@azure/cosmos");
                const endpoint = "https://localhost:8081";
                const key = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==";
                const client = new CosmosClient({ endpoint, key });    
                const { database } =  await client.databases.createIfNotExists({ id: 'SampleDatabase' });
                const { container } =  await database.containers.createIfNotExists({ id: 'SampleContainer' });
                const { sampleTrigger } = require('./Triggers/SampleTrigger.js')
                try {
                    await container.scripts.triggers.create(sampleTrigger)              
                } catch (e) {
                    if (e.code === 409) {
                        console.log('Trigger already exists replacing it with new version.')
                        await container.scripts.trigger(sampleTrigger.id).replace(sampleTrigger) 
                    } else {
                        throw(e)
                    }
                }
                finally {
                    const newItem = {
                        id: Math.floor(Math.random() * 10000).toString(),
                        name: 'Sample Item'
                    };
                    const options = { preTriggerInclude: ['SampleTrigger'] };
                    const { resource: trigger_result } = await container.items.create(newItem, options)
                    console.log(trigger_result) 
                }    
            }
            createTrigger().catch(error => {
                console.error("An error occurred: ", error);
            });

  QA:
    name: 'Quality Assurance'
    runs-on: ubuntu-latest
    environment: QA
    # needs: [Build, Testing]
    steps:
        - name: Repository checkout
          uses: actions/checkout@v4

        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }} # Generated with the following Azure CLI command: az ad sp create-for-rbac --name "myApp" --role owner --scopes /subscriptions/{subscription-id} --json-auth

        - name: Create Azure Resource Group
          run: | 
            az group create --name ${{ vars.RESOURCEGROUP }} --location eastus
            az role assignment create --assignee ${{ secrets.SERVICEPRINCIPAL }} --role owner --scope "/subscriptions/${{ secrets.AZURESUBID }}/resourcegroups/${{ vars.RESOURCEGROUP }}

        - name: Provisioning Azure resources
          id: arm_deployment
          uses: azure/arm-deploy@v1
          with:
            resourceGroupName: ${{ vars.RESOURCEGROUP }}
            template: IaC/cosmosdb.json
            parameters: IaC/cosmosdb.QA-parameters.json
            deploymentMode: 'Complete'

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: latest

        - name: Install NPM Azure Cosmos and Azure Identity dependencies
          run: npm install @azure/cosmos @azure/identity

        - name: Create and test Stored Procedure in Azure Cosmos DB
          uses: actions/github-script@v6
          with:
            script: |
              async function createSP() {       
                  const { CosmosClient } = require("@azure/cosmos");
                  const { DefaultAzureCredential } = require("@azure/identity");
                  const credential = new DefaultAzureCredential();
                  const cosmosClient = new CosmosClient({ 
                    endpoint: ${{ steps.arm_deployment.outputs.cosmosDBendpoint }}, 
                    aadCredentials: credential
                  });    
                  const { database } =  await cosmosClient.databases.createIfNotExists({ id: 'SampleDatabase' });
                  const { container } =  await database.containers.createIfNotExists({ id: 'SampleContainer' });
                  const { sampleStoredProcedure } = require('./StoredProcedures/SampleStoredProcedure.js');    
                  try {
                      await container.scripts.storedProcedures.create(sampleStoredProcedure)              
                  } catch (e) {
                      if (e.code === 409) {
                          console.log('Stored procedure already exists replacing it with new version.')
                          await container.scripts.storedProcedure(sampleStoredProcedure.id).replace(sampleStoredProcedure) 
                      } else {
                          throw(e)
                      }
                  }
                  finally{
                      const { resource: results } = await container.scripts.storedProcedure(sampleStoredProcedure.id).execute();
                      console.log(results);  
                  }
              }
              createSP().catch(error => {
                console.error("An error occurred: ", error);
              });
    
        - name: Create and test Trigger in Azure Cosmos DB
          uses: actions/github-script@v6
          with:
            script: |
              async function createTrigger() {
                const { CosmosClient } = require("@azure/cosmos");
                const { DefaultAzureCredential } = require("@azure/identity");
                const credential = new DefaultAzureCredential();
                const cosmosClient = new CosmosClient({ 
                  endpoint: ${{ steps.arm_deployment.outputs.cosmosDBendpoint }}, 
                  aadCredentials: credential
                });    
                const { database } =  await cosmosClient.databases.createIfNotExists({ id: 'SampleDatabase' });
                const { container } =  await database.containers.createIfNotExists({ id: 'SampleContainer' });
                const { sampleTrigger } = require('./Triggers/SampleTrigger.js')
                try {
                    await container.scripts.triggers.create(sampleTrigger)              
                } catch (e) {
                    if (e.code === 409) {
                        console.log('Trigger already exists replacing it with new version.')
                        await container.scripts.trigger(sampleTrigger.id).replace(sampleTrigger) 
                    } else {
                        throw(e)
                    }
                }
                finally {
                    const newItem = {
                        id: Math.floor(Math.random() * 10000).toString(),
                        name: 'Sample Item'
                    };
                    const options = { preTriggerInclude: ['SampleTrigger'] };
                    const { resource: trigger_result } = await container.items.create(newItem, options)
                    console.log(trigger_result) 
                }    
              }
              createTrigger().catch(error => {
                  console.error("An error occurred: ", error);
              });

        - name: Download web app artifact
          uses: actions/download-artifact@v3
          with:
            name: SampleApp
            path: SampleApp

        - name: Deploy web app to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ steps.arm_deployment.outputs.webappname }}
            package: SampleApp

  Production:
    name: 'Production Deployment'
    runs-on: ubuntu-latest
    environment: Production
    needs: QA
    steps:
        - name: Repository checkout
          uses: actions/checkout@v4

        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }} # For production, it is recommended to use a Service Principal with the least privileges possible that only has access to the production environment.

        - name: Create Azure Resource Group
          run: |
            az group create --name ${{ vars.RESOURCEGROUP }} --location eastus
            az role assignment create --assignee ${{ secrets.SERVICEPRINCIPAL }} --role owner --scope "/subscriptions/${{ secrets.AZURESUBID }}/resourcegroups/${{ vars.RESOURCEGROUP }}

        - name: Provisioning Azure Cosmos DB resource with ARM
          id: arm_deployment
          uses: azure/arm-deploy@v1
          with:
            resourceGroupName: ${{ vars.RESOURCEGROUP }}
            template: IaC/cosmosdb.json
            parameters: IaC/cosmosdb.Prod-parameters.json
            deploymentMode: 'Incremental'
            
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: latest

        - name: Install NPM Azure Cosmos and Azure Identity dependencies
          run: npm install @azure/cosmos @azure/identity
  
        - name: Create and test Stored Procedure in Azure Cosmos DB
          uses: actions/github-script@v6
          with:
            script: |
              async function createSP() {       
                  const { CosmosClient } = require("@azure/cosmos");
                  const { DefaultAzureCredential } = require("@azure/identity");
                  const credential = new DefaultAzureCredential();
                  const cosmosClient = new CosmosClient({ 
                    endpoint: ${{ steps.arm_deployment.outputs.cosmosDBendpoint }}, 
                    aadCredentials: credential
                  });    
                  const { database } =  await cosmosClient.databases.createIfNotExists({ id: 'SampleDatabase' });
                  const { container } =  await database.containers.createIfNotExists({ id: 'SampleContainer' });
                  const { sampleStoredProcedure } = require('./StoredProcedures/SampleStoredProcedure.js');    
                  try {
                      await container.scripts.storedProcedures.create(sampleStoredProcedure)              
                  } catch (e) {
                      if (e.code === 409) {
                          console.log('Stored procedure already exists replacing it with new version.')
                          await container.scripts.storedProcedure(sampleStoredProcedure.id).replace(sampleStoredProcedure) 
                      } else {
                          throw(e)
                      }
                  }
              }
              createSP().catch(error => {
                console.error("An error occurred: ", error);
              });
      
        - name: Create and test Trigger in Azure Cosmos DB
          uses: actions/github-script@v6
          with:
            script: |
              async function createTrigger() {
                const { CosmosClient } = require("@azure/cosmos");
                const { DefaultAzureCredential } = require("@azure/identity");
                const credential = new DefaultAzureCredential();
                const cosmosClient = new CosmosClient({ 
                  endpoint: ${{ steps.arm_deployment.outputs.cosmosDBendpoint }}, 
                  aadCredentials: credential
                });    
                const { database } =  await cosmosClient.databases.createIfNotExists({ id: 'SampleDatabase' });
                const { container } =  await database.containers.createIfNotExists({ id: 'SampleContainer' });
                const { sampleTrigger } = require('./Triggers/SampleTrigger.js')
                try {
                    await container.scripts.triggers.create(sampleTrigger)              
                } catch (e) {
                    if (e.code === 409) {
                        console.log('Trigger already exists replacing it with new version.')
                        await container.scripts.trigger(sampleTrigger.id).replace(sampleTrigger) 
                    } else {
                        throw(e)
                    }
                }    
              }
              createTrigger().catch(error => {
                  console.error("An error occurred: ", error);
              });
            
        - name: Download web app artifact
          uses: actions/download-artifact@v3
          with:
            name: SampleApp
            path: SampleApp

        - name: Deploy web app to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ steps.arm_deployment.outputs.webappname }}
            package: SampleApp